# Generated by Django 3.1 on 2020-12-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.JSONField(),
        ),
    ]
