"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os


AUTH_USER_MODEL = 'member.Member'


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c-!qd&54cz$i*u3%42!z1_svtl1sj$-&+^nsx7m&78cp((mui2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'staging.ractf.co.uk',
    'ractf.co.uk',
    '127.0.0.1',
    'localhost',
]

# Application definition

INSTALLED_APPS = [
    'team.apps.TeamConfig',
    'member.apps.MemberConfig',
    'authentication.apps.AuthConfig',
    'challenge.apps.ChallengeConfig',
    'challengeserver.apps.ChallengeserverConfig',
    'hint.apps.HintConfig',
    'leaderboard.apps.LeaderboardConfig',
    'config.apps.ConfigConfig',
    'plugins.apps.PluginsConfig',
    'websockets.apps.WebsocketsConfig',
    'scorerecalculator.apps.ScorerecalculatorConfig',
    'stats.apps.StatsConfig',
    'announcements.apps.AnnouncementsConfig',
    'ractf.apps.RactfConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'django_zxcvbn_password_validator',
    'channels',
    'storages',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

if DEBUG:
    INSTALLED_APPS += ['silk']

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE += ['silk.middleware.SilkyMiddleware']

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'websockets.routing.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}



# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ractf',
        'USER': 'ractf',
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'django_zxcvbn_password_validator.ZxcvbnPasswordValidator',
    },

]


PASSWORD_MINIMAL_STRENGTH = 3


AUTHENTICATION_BACKENDS = ['backend.backends.EmailOrUsernameBackend']


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/api/v2/static/'
STATIC_ROOT = '/srv/django_static'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'backend.renderers.RACTFJSONRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer'
    ),
    'EXCEPTION_HANDLER': 'backend.exception_handler.handle_exception',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'backend.authentication.RactfTokenAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'backend.throttling.AdminBypassThrottle',
    ],
    # These are completely arbitrary and chosen at 3am, TODO: reconsider them
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/minute',
        'register': '10/minute',
        '2fa': '1000/day',
        'password_reset': '3/minute',
        'request_password_reset': '5/hour',
        'verify_email': '3/minute',
        'change_password': '10/minute',
        'challenges': '99999/minute',
        'flag_submit': '10/minute',
        'hint': '5/minute',
        'use_hint': '3/minute',
        'leaderboard': '5/minute',
        'self': '3/minute',
        'member': '10/minute',
        'team': '10/minute',
        'team_create': '3/hour',
        'team_join': '5/minute',
        'config': '100/minute',
        'file': '100/minute',
        'challenge_instance_get': '20/minute',
        'challenge_instance_reset': '10/hour',
        'announcement': '100/minute',
    },
    'DEFAULT_PAGINATION_CLASS': 'backend.pagination.FastPagination',
    'PAGE_SIZE': 100,
}

MAIL_SOCK_URL = 'http+unix://%2Ftmp%2Fmailusv.sock/send'
SEND_MAIL = False
FRONTEND_URL = 'https://staging.ractf.co.uk/'
CHALLENGE_SERVER_URL = 'http://challenges.ractf.co.uk'
CHALLENGE_SERVER_API_KEY = 'api-key'
CHALLENGE_SERVER_IP = '123.321.13.37'  # shown to participants

INSTALLED_PLUGINS = [
    'plugins.flag.hashed',
    'plugins.flag.plaintext',
    'plugins.flag.regex',
    'plugins.flag.lenient',
    'plugins.flag.long_text',
    'plugins.flag.map',
    'plugins.points.basic',
    'plugins.points.decay',
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CACHES = {
    'default': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': '127.0.0.1:6379',
        'OPTIONS': {
            'DB': 0,
            'PASSWORD': None,
            'PARSER_CLASS': 'redis.connection.HiredisParser',
            'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 50,
                'timeout': 20,
            },
            'MAX_CONNECTIONS': 1000,
            'PICKLE_VERSION': -1,
        }
    }
}

CONFIG = {
    'BACKEND': 'config.backends.RedisBackend',
    'REDIS': {
        'HOST': '127.0.0.1',
        'PORT': 6379,
        'PASSWORD': None,
        'DB': 2,
    }
}
