# Generated by Django 3.1.4 on 2020-12-23 16:23

from django.db import migrations, models

import challenges


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', "0007_file_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="upload",
            field=models.FileField(null=True, upload_to=challenges.logic.get_file_path),
        ),
    ]
