# Generated by Django 3.1.4 on 2020-12-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20201223_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='md5',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
