# Generated by Django 3.1 on 2020-12-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_auto_20201225_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='challenge_metadata',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='flag_metadata',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
