# Generated by Django 3.1 on 2021-03-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', "0015_auto_20210131_1809"),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name="unlock_requirements",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
