# Generated by Django 3.2.4 on 2021-06-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_auto_20210327_2315'),
        ('challenges', '0016_auto_20210408_1804'),
    ]

    operations = [
    ]
