from django.dispatch import Signal

flag_score = Signal()
flag_reject = Signal()
flag_submit = Signal()
team_join = Signal()
team_join_attempt = Signal()
team_join_reject = Signal()
team_create = Signal()
use_hint = Signal()
logout = Signal()
add_2fa = Signal()
verify_2fa = Signal()
remove_2fa = Signal()
password_reset = Signal()
password_reset_start = Signal()
password_reset_start_reject = Signal()
email_verified = Signal()
change_password = Signal()
login = Signal()
login_reject = Signal()
register = Signal()
register_reject = Signal()
websocket_connect = Signal()
websocket_disconnect = Signal()
