from django.dispatch import Signal

flag_score = Signal(providing_args=['user', 'team', 'challenge', 'flag', 'solve'])
flag_reject = Signal(providing_args=['user', 'team', 'challenge', 'flag', 'reason'])
flag_submit = Signal(providing_args=['user', 'team', 'challenge', 'flag'])
team_join = Signal(providing_args=['user', 'team'])
team_join_attempt = Signal(providing_args=['user', 'team_name'])
team_join_reject = Signal(providing_args=['user', 'team_name'])
team_create = Signal(providing_args=['team'])
use_hint = Signal(providing_args=['user', 'team', 'hint'])
logout = Signal(providing_args=['user'])
add_2fa = Signal(providing_args=['user'])
verify_2fa = Signal(providing_args=['user'])
password_reset = Signal(providing_args=['user'])
password_reset_start = Signal(providing_args=['user'])
password_reset_start_reject = Signal(providing_args=['email'])
email_verified = Signal(providing_args=['user'])
change_password = Signal(providing_args=['user'])
login = Signal(providing_args=['user'])
login_reject = Signal(providing_args=['username', 'reason'])
register = Signal(providing_args=['user'])
register_reject = Signal(providing_args=['username', 'email'])
websocket_connect = Signal(providing_args=['channel_layer'])
websocket_disconnect = Signal(providing_args=['channel_layer'])
