# Generated by Django 4.0.2 on 2022-02-11 21:43

import backend.validators
from django.db import migrations, models
import django.db.models.functions.text


def truncate_usernames(apps, schema_editor):
    Team = apps.get_model('team', 'team')
    db_alias = schema_editor.connection.alias
    for team in Team.objects.using(db_alias).all():
        if len(team.name) > 36:
            team.name = team.name[:36]
            team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_size_limit_exempt'),
    ]

    operations = [
        migrations.RunPython(
            truncate_usernames,
            # Marked as elidable since when we squash we will have the 36 characters
            # in by default
            elidable=True,
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=36, unique=True, validators=[backend.validators.printable_name]),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='team_team_username_uniq_idx'),
        ),
    ]
