# Generated by Django 3.1.1 on 2020-09-27 22:56

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_size_limit_exempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=36, unique=True, validators=[backend.validators.printable_name]),
        ),
    ]
