# Generated by Django 4.0.4 on 2022-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_name_team_team_team_username_uniq_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='suspended_reason',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
