# Generated by Django 4.2.6 on 2023-10-08 17:34

import backend.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0004_alter_team_name_team_team_team_username_uniq_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=31, unique=True, validators=[backend.validators.printable_name])),
                ("description", models.TextField(blank=True, max_length=255)),
                ("is_self_assignable", models.BooleanField(default=True)),
                ("has_own_leaderboard", models.BooleanField(default=True)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin("leaderboard_group"), models.Model),
        ),
        migrations.AddField(
            model_name="team",
            name="leaderboard_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to="team.leaderboardgroup",
            ),
        ),
    ]
