# Generated by Django 3.0.5 on 2020-08-05 11:50

import django.contrib.postgres.fields.citext
from django.db import migrations
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_team_last_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=36, unique=True, validators=[team.models.printable_name]),
        ),
    ]
