# Generated by Django 3.0.5 on 2020-08-08 15:49

import django.contrib.postgres.fields.citext
from django.db import migrations

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teams', "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=36, unique=True, validators=[core.validators.printable_name]),
        ),
    ]
