# Generated by Django 3.0.5 on 2020-08-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20200808_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='size_limit_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
