# Generated by Django 3.0.5 on 2020-09-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='upload',
            field=models.FileField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
