# Generated by Django 3.1.1 on 2020-09-27 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_size_limit_exempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0006_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_metadata',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag_metadata',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('text', models.TextField()),
                ('penalty', models.IntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_set', to='challenge.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='HintUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints_used', to='challenge.challenge')),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='challenge.hint')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hints_used', to='team.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hints_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hint', 'team')},
            },
        ),
    ]
