# Generated by Django 3.1.4 on 2020-12-23 16:23

from django.db import migrations, models

import challenge.models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(null=True, upload_to=challenge.models.get_file_name),
        ),
    ]
