# Generated by Django 3.0.5 on 2020-09-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20200906_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.TextField(default='yes', max_length=255),
            preserve_default=False,
        ),
    ]
