# Generated by Django 3.0.5 on 2020-09-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20200906_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(),
        ),
    ]
