# Generated by Django 3.1.5 on 2021-01-31 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_migrate_legacy_unlocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='unlocks',
        ),
    ]
