# Generated by Django 3.1 on 2021-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_auto_20210131_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='unlock_requirements',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
