# Generated by Django 3.2.4 on 2021-07-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0018_challenge_tiebreaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='tiebreaker',
            field=models.BooleanField(default=True),
        ),
    ]
