# Generated by Django 3.2.4 on 2021-07-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0019_score_tiebreaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='tiebreaker',
            field=models.BooleanField(default=True, help_text='Should the challenge be able to break ties?'),
        ),
        migrations.AlterField(
            model_name='score',
            name='tiebreaker',
            field=models.BooleanField(default=True, help_text='Should the score be able to break ties?'),
        ),
    ]
