# Generated by Django 3.2.4 on 2021-07-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0020_auto_20210729_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
