# Generated by Django 4.0.4 on 2022-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0022_challenge_current_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
