# Generated by Django 3.0.5 on 2020-09-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20200911_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
