# Generated by Django 3.0.5 on 2020-08-08 15:49

import backend.validators
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200808_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 36 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=36, unique=True, validators=[backend.validators.printable_name], verbose_name='username'),
        ),
    ]
