# Generated by Django 3.0.5 on 2020-08-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20200810_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
