# Generated by Django 3.1.1 on 2020-09-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
