# Generated by Django 3.2.4 on 2021-06-09 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20201226_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password_reset_token',
        ),
    ]
