# Generated by Django 4.0.2 on 2022-05-01 19:51

from django.db import migrations, models
from django.conf import settings

def fix_ip_addresses(apps, schema_editor):
    UserIP = apps.get_model('member', 'userip')
    db_alias = schema_editor.connection.alias
    for userip in UserIP.objects.using(db_alias).all():
        userip.ip = userip.ip.split(",")[0]
        userip.save()

class Migration(migrations.Migration):
    dependencies = [
        ('member', '0009_alter_member_options_alter_member_username_and_more'),
    ]

    operations = [
        migrations.RunPython(
            fix_ip_addresses,
            # Marked as elidable as all new IP addresses will be in the correct format
            elidable=True,
        ),
        migrations.AlterField(
            model_name='userip',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='userip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL,
                                    related_name='ips', to=settings.AUTH_USER_MODEL),
        ),
    ]
