# Generated by Django 4.0.4 on 2022-05-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_fix_client_ip_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='suspended_reason',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
