# Generated by Django 3.0.5 on 2020-08-16 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
